/*
** test_vm.c
** Integration test for the standalone Lua VM (libluavm).
**
** This program validates that the standalone VM can:
**   1. Create and close a Lua state
**   2. Open standard libraries
**   3. Load and execute precompiled bytecode
**   4. Perform stack operations and function calls
**   5. Reject text chunks gracefully
**   6. Handle errors properly
**
** Build:
**   gcc -o test_vm tests/test_vm.c -I. -L. -lluavm -lm -ldl
**
** Run:
**   LD_LIBRARY_PATH=. ./test_vm
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "luavm.h"


static int tests_passed = 0;
static int tests_failed = 0;

#define TEST(name) \
  printf("  %-50s ", name); fflush(stdout)

#define PASS() \
  do { printf("[PASS]\n"); tests_passed++; } while (0)

#define FAIL(msg) \
  do { printf("[FAIL] %s\n", msg); tests_failed++; } while (0)


/*
** Helper: compile a Lua source string to bytecode using a full Lua state.
** Since we test the VM-only library, we pre-generate bytecode.
** This function is only used to embed bytecode as C arrays.
*/


/* --- Precompiled bytecode arrays --- */

/*
** Bytecode for: return 42
** Generated by: luac -o - -s <<< "return 42"
** Embedded as a C array.
*/
static const unsigned char bytecode_return42[] = {
  /* placeholder - will be filled by the test setup script */
  0
};
static size_t bytecode_return42_len = 0;

/*
** Bytecode for: print("Hello from VM!")
*/
static const unsigned char bytecode_hello[] = {
  0
};
static size_t bytecode_hello_len = 0;


/* Flag indicating whether bytecode was loaded from files */
static int bytecode_from_files = 0;

/* Buffers for file-loaded bytecode */
static unsigned char *filebuf_return42 = NULL;
static size_t filebuf_return42_len = 0;
static unsigned char *filebuf_hello = NULL;
static size_t filebuf_hello_len = 0;


static unsigned char *load_file(const char *path, size_t *out_len) {
  FILE *f = fopen(path, "rb");
  unsigned char *buf;
  long len;
  if (!f) return NULL;
  fseek(f, 0, SEEK_END);
  len = ftell(f);
  fseek(f, 0, SEEK_SET);
  buf = (unsigned char *)malloc((size_t)len);
  if (!buf) { fclose(f); return NULL; }
  if (fread(buf, 1, (size_t)len, f) != (size_t)len) {
    free(buf);
    fclose(f);
    return NULL;
  }
  fclose(f);
  *out_len = (size_t)len;
  return buf;
}


static void load_bytecode_files(void) {
  filebuf_return42 = load_file("samples/return42.luac", &filebuf_return42_len);
  filebuf_hello = load_file("samples/hello.luac", &filebuf_hello_len);
  if (filebuf_return42 && filebuf_hello)
    bytecode_from_files = 1;
}


static const unsigned char *get_return42(size_t *len) {
  if (bytecode_from_files) {
    *len = filebuf_return42_len;
    return filebuf_return42;
  }
  *len = bytecode_return42_len;
  return bytecode_return42;
}

static const unsigned char *get_hello(size_t *len) {
  if (bytecode_from_files) {
    *len = filebuf_hello_len;
    return filebuf_hello;
  }
  *len = bytecode_hello_len;
  return bytecode_hello;
}


/* ====================== Test Cases ====================== */

static void test_state_creation(void) {
  lua_State *L;
  TEST("State creation and destruction");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }
  lua_close(L);
  PASS();
}


static void test_open_libs(void) {
  lua_State *L;
  TEST("Open standard libraries");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }
  luaL_openlibs(L);
  /* Verify that the 'print' function is available */
  lua_getglobal(L, "print");
  if (!lua_isfunction(L, -1)) {
    FAIL("'print' not found after openlibs");
    lua_close(L);
    return;
  }
  lua_pop(L, 1);
  lua_close(L);
  PASS();
}


static void test_stack_operations(void) {
  lua_State *L;
  TEST("Stack operations (push/get)");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }

  lua_pushinteger(L, 100);
  lua_pushnumber(L, 3.14);
  lua_pushstring(L, "test");
  lua_pushboolean(L, 1);
  lua_pushnil(L);

  if (lua_gettop(L) != 5) { FAIL("wrong stack size"); lua_close(L); return; }
  if (!lua_isnil(L, -1)) { FAIL("top should be nil"); lua_close(L); return; }
  if (!lua_isboolean(L, -2)) { FAIL("should be boolean"); lua_close(L); return; }
  if (!lua_isstring(L, -3)) { FAIL("should be string"); lua_close(L); return; }
  if (lua_tointeger(L, 1) != 100) { FAIL("wrong integer value"); lua_close(L); return; }

  lua_close(L);
  PASS();
}


static void test_table_operations(void) {
  lua_State *L;
  TEST("Table operations");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }

  lua_newtable(L);
  lua_pushstring(L, "hello");
  lua_setfield(L, -2, "key");
  lua_getfield(L, -1, "key");
  if (strcmp(lua_tostring(L, -1), "hello") != 0) {
    FAIL("wrong table value");
    lua_close(L);
    return;
  }
  lua_pop(L, 2);

  lua_close(L);
  PASS();
}


static int noop_cfunc(lua_State *L) {
  (void)L;
  return 0;
}


static void test_c_function_call(void) {
  lua_State *L;
  TEST("C function call from VM");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }

  lua_pushcfunction(L, noop_cfunc);
  lua_pop(L, 1);

  lua_pushinteger(L, 10);
  lua_pushinteger(L, 20);
  lua_arith(L, LUA_OPADD);
  if (lua_tointeger(L, -1) != 30) {
    FAIL("arithmetic operation failed");
    lua_close(L);
    return;
  }
  lua_pop(L, 1);

  lua_close(L);
  PASS();
}


static void test_load_bytecode(void) {
  lua_State *L;
  int status;
  size_t len;
  const unsigned char *bc;
  TEST("Load and execute bytecode (return 42)");

  bc = get_return42(&len);
  if (len == 0) {
    printf("[SKIP] no bytecode available\n");
    return;
  }

  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }
  luaL_openlibs(L);

  status = luaVM_loadbytecode(L, (const char *)bc, len, "return42");
  if (status != LUA_OK) {
    FAIL(lua_tostring(L, -1));
    lua_close(L);
    return;
  }

  status = lua_pcall(L, 0, 1, 0);
  if (status != LUA_OK) {
    FAIL(lua_tostring(L, -1));
    lua_close(L);
    return;
  }

  if (!lua_isinteger(L, -1) || lua_tointeger(L, -1) != 42) {
    FAIL("expected return value 42");
    lua_close(L);
    return;
  }

  lua_close(L);
  PASS();
}


static void test_load_hello(void) {
  lua_State *L;
  int status;
  size_t len;
  const unsigned char *bc;
  TEST("Load and execute bytecode (hello)");

  bc = get_hello(&len);
  if (len == 0) {
    printf("[SKIP] no bytecode available\n");
    return;
  }

  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }
  luaL_openlibs(L);

  status = luaVM_loadbytecode(L, (const char *)bc, len, "hello");
  if (status != LUA_OK) {
    FAIL(lua_tostring(L, -1));
    lua_close(L);
    return;
  }

  status = lua_pcall(L, 0, 0, 0);
  if (status != LUA_OK) {
    FAIL(lua_tostring(L, -1));
    lua_close(L);
    return;
  }

  lua_close(L);
  PASS();
}


static void test_reject_text(void) {
  lua_State *L;
  int status;
  const char *source = "return 1 + 2";
  TEST("Reject text chunks in VM-only mode");

  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }

  status = luaL_loadbufferx(L, source, strlen(source), "text", "t");
  if (luaVM_hasparser(L)) {
    /* Full build - text loading should succeed */
    if (status != LUA_OK) {
      FAIL("text loading should succeed in full build");
      lua_close(L);
      return;
    }
  } else {
    /* VM-only build - text loading should fail */
    if (status == LUA_OK) {
      FAIL("text loading should fail in VM-only mode");
      lua_close(L);
      return;
    }
  }

  lua_close(L);
  PASS();
}


static void test_gc(void) {
  lua_State *L;
  TEST("Garbage collection");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }
  luaL_openlibs(L);

  /* Create some garbage */
  lua_newtable(L);
  lua_pushstring(L, "some data");
  lua_setfield(L, -2, "key");
  lua_pop(L, 1);

  /* Force GC */
  lua_gc(L, LUA_GCCOLLECT);

  lua_close(L);
  PASS();
}


static void test_coroutine(void) {
  lua_State *L, *co;
  TEST("Coroutine creation");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }

  co = lua_newthread(L);
  if (co == NULL) { FAIL("lua_newthread returned NULL"); lua_close(L); return; }

  lua_pop(L, 1);
  lua_close(L);
  PASS();
}


static void test_error_handling(void) {
  lua_State *L;
  int status;
  TEST("Error handling (pcall)");
  L = luaL_newstate();
  if (L == NULL) { FAIL("luaL_newstate returned NULL"); return; }
  luaL_openlibs(L);

  /* Load invalid bytecode */
  status = luaVM_loadbytecode(L, "invalid", 7, "bad");
  if (status == LUA_OK) {
    FAIL("should have failed loading invalid bytecode");
    lua_close(L);
    return;
  }
  lua_pop(L, 1);  /* pop error message */

  lua_close(L);
  PASS();
}


/* ====================== Main ====================== */

int main(int argc, char *argv[]) {
  (void)argc; (void)argv;

  printf("=== Lua VM Integration Tests ===\n\n");

  /* Try to load bytecode from sample files */
  load_bytecode_files();
  if (bytecode_from_files)
    printf("  (Using bytecode from samples/ directory)\n\n");
  else
    printf("  (No sample bytecode found, some tests will be skipped)\n\n");

  test_state_creation();
  test_open_libs();
  test_stack_operations();
  test_table_operations();
  test_c_function_call();
  test_load_bytecode();
  test_load_hello();
  test_reject_text();
  test_gc();
  test_coroutine();
  test_error_handling();

  printf("\n=== Results: %d passed, %d failed ===\n",
         tests_passed, tests_failed);

  /* Cleanup */
  free(filebuf_return42);
  free(filebuf_hello);

  return tests_failed > 0 ? 1 : 0;
}
